compile1:
# 	Compile your code for first part here
	gcc -o Q1_part1.out Q1_part1.c

run1: compile1
# 	 Execute part 1 here
	./Q1_part1.out

compile2:
# 	Compile your code for second part here
	gcc Q1_part2.c -o Q1_part2.out -lpthread

run2: compile2
#	Execute part 2 here
	./Q1_part2.out